### ISSUE TITLE
US 1: Create Pages with simple layout

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#1]
## Value Proposition

**As a** User 
**I want to** navigate to pages through url routes
**in order to** to see their simple layout contents
​

## Description

![US1-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/b053e231-ebcc-4483-af83-367ca1418c0c)

## Acceptance Criteria

- [ ] Writing any of the folloing routes `/`, `/content`, `/new-folder`, `/new-entry`, `/<folder-id>`, `/<folder-id>/<entry-id>`, `/content/<entry-id>` should navigate me to a page
- [ ] All pages need to have a title containing the app's name on top of the page
- [ ] All pages need to have a text underneath the big title, displaying a breadcrumb of the current page location
- [ ] All pages breadcrumbs need to have solid border lines above and bellow
- [ ] The `/` route page (Dashboard) underneath the breadcrumb border line, needs a `Recent Uploads` text and a dashed dividing line underneath it
      ​

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us1/create-pages-w-simple-layout`
- [ ] create the page files in a hierarchy revelant to the first acceptance criteria routes
- [ ] create `Header` component
- [ ] create `Breadcrumb` component
- [ ] use the router hook in `Breadcrumb` component
- [ ] create `RecentUploads` component
- [ ] apply the `Header` and `Breadcrumb` components to all pages
- [ ] apply the `RecentUploads` component to the `/` route page

**Comment by dimitriosxmi** [comment]
I was thinking of always linking at the bottom of the user stories the previous and the next user story, would that be alright ?

**Comment by mbosselmann** [comment]
Hi Dimi,
well done! I can see that you put a lot of thought into your first user story and wrote it down in many steps. That's great! 💪  Nevertheless, I have a few comments and also a question. I will start with my question:

- Can you describe the purpose of your app for me in short? I am not sure if I am understanding it correctly. 🤔 I assume that you want to build something like a Dropbox clone?

## Description
- The dotted border can be confused with the edge of the mobile screen. I would recommend to remove it for more clarity. :)

> I was thinking of always linking at the bottom of the user stories the previous and the next user story, would that be alright ?
- To answer your question: You can link to user stories if you like. I would prefer to link to previous user stories that are relevant to the feature you want to implement. And I would add the link in the description part of your user story as the linking then completes the description.
- Instead of having "US 1: Dashboard with simple layout" above the wireframe I would update the title of this issue and remove it from the description. 🤔 
- If my assumption about the purpose of your app is correct, then there will be no uploaded files for now. You could show that by displaying a text below "Recent Uploads". An example: "No uploaded files yet." (That the text is displayed should then be another acceptance criterion.)

## Tasks
- " if router is / display Dashboard in Breadcrumb text" - I think this part is not necessary yet as you will have only one page after implementing your first user story. I recommend to implement this later when you have more than one page.

I hope this does help! Feel free to ask me if you have further questions. :)

**Comment by dimitriosxmi** [comment]
Hi Mareike,
Thank you for yout review and your time 😄 

>     * Can you describe the purpose of your app for me in short? I am not sure if I am understanding it correctly. 🤔 I assume that you want to build something like a Dropbox clone?

The application is going to be an organizer for the reference files the artists find online when they are working on their crafts, could be a screenshot from a video, an uploaded picture of real life or an image of another artist's work which they will ultimately use as point of reference for their own current piece of work during their workflow.
This current page represents the `Homepage` namely `Dashboard` where the `User` will have the ability to access their most recent content and their folders, so far given the present user story there's only supposed to be a Headline with the WebApp name `ARO` (stands for Artist's Reference Organizer)

**Comment by dimitriosxmi** [comment]
Thank you for the feedback regarding my question as well as the recommendation with the title and especially the `Recent Uploads` I love that one! 🧠 💯

**Comment by mbosselmann** [comment]
Hi Dimi,
thank you very much for your description! Now I understand the purpose of your app much better. This is a very cool idea!

Since the implementation of an image upload won't happen until after the Cloudinary workshop (I think?), for your first user story you might consider showing a list of sample references on the dashboard page. Then, in the following user stories, you can also use the example data when it comes to showing different references for different art projects. 🤔 

What do you think about my suggestion?

**Comment by dimitriosxmi** [comment]
Heyo Mareike,

Thank you very much for your time and review :D 

> What do you think about my suggestion?

It's a nice suggestion however the uploaded files will appear as entries and the way I have handled entries so far they are not containing images yet (and I have already created wireframes for a totlal of 16 User Stories)

So for the time being I do not worry about the cloudinary workshop coming up to early, worst case I can add the image uploading at the third week 😉

**Comment by mbosselmann** [comment]
Hi Dimi,
ok! Thank you for your explanation. 💪 
Then I will approve your first user story. 🥳
