### ISSUE TITLE
US9: Entry View

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#16]
## Value Proposition

**As a** user
**I want to** click on an entry listing to enter it's entry view page
**in order to** read more details about the specific entry i clicked on
​

## Description

![US9-ARO+ContentPageRef](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/770ce159-87ef-4b7d-aced-68c9fa1c2628)
> ## ​On the right we have a content page reference for the layout

## Acceptance Criteria

- [ ] `Entry preview` must be wrapped in a `Link`
- [ ] Clicking `Entry preview` must navigate me to the corresponding `Entry view` page
- [ ] `Entry view` page must have the same layout as the `Content` page does regarding the `Header`, `Breadcrumb`, `Side bar`, and `Back button`
- [ ] When I'm located in a `Entry view` page the `Breadcrumb` must be something similar to `Dashboard/ <entryName>`
- [ ] `Entry view` page must contain an `Entry details`
- [ ] `Entry details` must have the full name of the entry displayed in the top center

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us9/entry-view` and navigate into it
- [ ] update `EntryPreview` component
- [ ] create `EntryView` page file
- [ ] apply to `EntryView` page the `CommonHeaderLayout`, and `BackButton`, components with the same layout as `Content` page does
- [ ] create `EntryDetails` component
- [ ] apply to `EntryView` page the `EntryDetails` component underneath the `BackButton` component

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/8)
[Next US (pending)]()

**Comment by matschi3** [comment]
LGTM!
very detailed, i've nothing to apply here
