### ISSUE TITLE
US 10: Delete Folder Button

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#17]
## Value Proposition

**As a** user 
**I want to** click a button to delete a folder
**so that** I can remove folders that I don't need anymore
​

## Description

![US10-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/ee9ad534-bed5-4d21-b075-de80066fbaaf)
​

## Acceptance Criteria

- [ ] `Folder view` page must habe a `Delete` botton on the top right
- [ ] `Delete` button must have the text `❌ Delete Folder`
- [ ] Clicking the `Delete` button must open up a `Delete request`
- [ ] `Delete request` must contain the text `Are you sure you want to delete this folder?` on the top center
- [ ] `Delete request` must have a 2 buttons placed horizontally undeneath the text
  - [ ] `Delete request` left button must have the text `Confirm Deletion`
  - [ ] Clicking the left button inside `Delete request` must delete the folder from the database and navigate the user to the dashboard route `/`
  - [ ] `Delete request` right button must have the text `Cancel`
  - [ ] Clicking the right button inside `Delete request` must close the `Delete request`
- [ ] Clicking outside the `Delete request` must close the `Delete request`
      ​

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us10/delete-folder-button` and navigate into it
- [ ] create `DeleteButton` component
- [ ] create `DeleteRequest` component
- [ ] apply to `DeleteButton` component the `DeleteRequest` component
- [ ] apply to `FolderView` page the `DeleteButton` component

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/16)
[Next US (pending)]()

**Comment by matschi3** [comment]
i assume in your task 'create component' all function creation happens.
so good to go!
really like that pop-up delete 😎

**Comment by dimitriosxmi** [comment]
You asumed correctly 😄 given all the important instructions for the dev are in the acceptance criteria, I only than have to mention some rough technicalities in the tasks that collectively do what the acceptance criteria describe
