### ISSUE TITLE
US 11: Delete Entry Button

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#18]
## Value Proposition

**As a** user 
**I want to** click a button to delete an entry
**so that** I can remove entries that I don't need anymore
​

## Description

![US11-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/6793eae8-f3ca-47bf-9731-37039831a860)
​

## Acceptance Criteria

- [ ] `Entry view` page must have a `Delete` button on the top right
- [ ] `Delete` button must have the text `❌ Delete Entry`
- [ ]  Clicking the `Delete` button must open up a `Delete request`
- [ ] `Delete request` must contain the text `Are you sure you want to delete this entry?` on the top center
- [ ] `Delete request` must have a 2 buttons placed horizontally undeneath the text
  - [ ] `Delete request` left button must have the text `Confirm Deletion`
  - [ ] Clicking the left button inside `Delete request` must delete the entry from the database AND navigate the user to the dashboard route `/` IF however the entry had a value of a folder on it's `selected folder` property than the user must be navigated to the specific folder route
  - [ ] `Delete request` right button must have the text `Cancel`
  - [ ] Clicking the right button inside `Delete request` must close the `Delete request`
- [ ] Clicking outside the `Delete request` must close the `Delete request`
      ​

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us11/delete-entry-button` and navigate into it
- [ ] update `DeleteButton` component
- [ ] update `DeleteRequest` component
- [ ] apply to `EntryView` page the `DeleteButton` component with the proper props

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/17)
[Next US (pending)]()

**Comment by MariaRiosNavarro** [comment]
Wow that's what I call a detailed job, I'm looking forward to seeing how it turns out. 🚀
