### ISSUE TITLE
US 12: Create Entry - More Fields

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#19]
## Value Proposition

**As a** user
**I want to** have 3 more fields in my entry creation, namely one for a refrence link, one for a description and one for tags
**so that** I can get more specific and detailed with my entries
​

## Description

![US12-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/7f7a1aa3-2f3a-4bb8-9b3d-0609a170a7db)
​

## Acceptance Criteria

- [ ] `New entry form` must have an input field for the entry reference link underneath the entry name input field
- [ ] The entry reference link input field inside `New entry form` must have the text above `Reference a Link:`
- [ ] `New entry form` must have a `Description` section with an input field for the entry description underneath the entry reference link input field
- [ ] `New entry form` must have a `Tags` section with multi-select field with a label text `Use Tag:` on the left
- [ ] The `Tags` section inside `New entry form` must have a `New Tag:` label underneath the multi-select field AND the label must be to the left of an input field  which must be between a tag creation button which must have the text `➕ Add Tag`
      ​

## Tasks

- [ ]  switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us12/create-entry-more-fields` and navigate into it
- [ ] update `NewEntryForm`

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/18)
[Next US (pending)]()

**Comment by MariaRiosNavarro** [comment]
Another work of art, you are very detailed, but I don't know if the "I want to" in your Value Proposition might be too technical. But I don't know how to put it more simply either, so it's fine by me.🚀

**Comment by dimitriosxmi** [comment]
Ye I was kinda worried it might be a tad too detailed, but I don't know how to define it either given the US 13 is to add one more field in this form 😓 😄
