### ISSUE TITLE
US 2: Side Bar

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#2]
## Value Proposition

**As a**  User
**I want to** have a toggleable side bar through a burger button on top left of the page
**so that** I can toggle the side bar and use it to navigate to the dashboard
​

## Description

![US2-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/e9fab533-0dc3-4dd1-bf0a-9ed09932298e)

## Acceptance Criteria

- [ ] A `burger` icon button must exist on the top left corner of the `Homepage` at the `Headline` level
- [ ] `burger` icon must be clickable
- [ ] Clicking the `burger` icon the  `burger` icon must change to an `x` icon
- [ ] Clicking the `burger` icon must open the `Side bar`
- [ ] `Side bar` must have the `x` icon button on the top left
- [ ] `Side bar` must have a button with the text `🏠 Dashboard` which navigates to the `Homepage`
- [ ] Clicking the `x` icon must close the `Side bar`
- [ ] `Side bar` must be on the left side of the and render above and overlay the `Homepage`
      ​

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us2/side-nav-bar`
- [ ] Add a `burger` icon file
- [ ] Add a `x` icon file
- [ ] create `SideBar` component
- [ ] create `SideBarButton` component
- [ ] apply the components in the `/` route page

**Comment by rueveydaakuel** [comment]
The user story is clear and quite understandable. LGTM 👍

**Comment by dimitriosxmi** [comment]
> The user story is clear and quite understandable. LGTM 👍

Thank you for your time and for the review @rueveydaakuel 😊
