### ISSUE TITLE
US 13: Create Entry - Folder Selection

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#20]
## Value Proposition

**As a** use
**I want to** have a dropdown button in my entry creation that allows me to select a folder
**so that** I can easily define in which folder I want my entry to land in
​

## Description

![US13-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/cc53faf3-8e30-4c59-82d3-ac5308bea711)

## Acceptance Criteria

- [ ] `New entry form` must have a `Folder Selection` section with a dropdown button
- [ ] Clicking the dropdown button inside `Folder Selection` section inside `New entry form` must open a list of all available folders
- [ ] Selecting an option from the dropdown button inside `Folder Selection` section inside `New entry form` must close the dropdown and display in the dropdown button text the option the user selected
      ​

## Tasks

- [ ] witch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us13/create-entry-folder-selection` and navigate into it
- [ ] update `NewEntryForm` component

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/19)
[Next US (pending)]()

**Comment by matschi3** [comment]
nice and small US 👍🏼
good to go 🚀

**Comment by matschi3** [comment]
works as it should!
🚀
