### ISSUE TITLE
US 14: Entry View - More Details

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#21]
## Value Proposition

**As a** user
**I want to** see more details such as the link, the tags and the description when I am viewing an entry
**so that** I can be better informed in the future of the entry I created before
​

## Description

![US14-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/cfee27b6-b443-45fd-aad3-ed6b4d15fb6c)

## Acceptance Criteria

- [ ] `Entry details` must have a text `Link:` with a text containing the link value of the entry and a dashed bottom border, displayed underneath the `Link:` text
- [ ] Text `Link:` must be displayed underneath the entry name text
- [ ] `Entry details` must have a text `Tags:` with the entry's tag values on the right of the text and a dashed bottom border, displayed underneath the text that contains the link value of the entry
- [ ] `Entry details` must have a text `Description:` with a text contaning the description value of the entry, displayed underneath the entry's tag values 
      ​

## Tasks

- [ ] witch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us14/entry-view-more-details` and navigate into it
- [ ] update `EntryDetails` component

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/20)
[Next US (pending)]()

**Comment by matschi3** [comment]
LGTM 👍🏼
nice descriptive
