### ISSUE TITLE
US 15: Entry View - Edit Mode

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#22]
## Value Proposition

**As a** user
**I want to** edit the entry I am currently viewing
**in order to** make changes to it
​

## Description

![US15-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/83f37941-8f38-4fdb-864e-097ff98d3da9)
​

## Acceptance Criteria

- [ ] `Entry view` page must have an `Edit` button positioned fixed on the bottom right of the screen
- [ ] The `Edit` button must have the same `file` icon but as the `New Entry` button, but a different color AND instead of a `plus` icon it must have a `pen` icon
- [ ] `New entry form` must now be changed to `Entry form`
- [ ] Clicking the `Edit` button must toggle the `Entry details` off and the `Entry form` on
- [ ] `Entry form` must be filled with all the entry's values
- [ ] The submit button on bottom of the `Entry form` must have a `pen` icon instead of a `plus` icon
- [ ] Clicking the submit button on the bottom of the `Entry form` must apply the changes to the entry in the database AND toggle the "Entry form' off and the 'Enty details' on
- [ ] Clicking the back button while the `Entry form` is toggled on must toggle the `Entry form` off and the `Entry details` on without saving any of the changes
      ​

## Tasks

- [ ]  switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us15/entry-view-edit-mode` and navigate into it
- [ ] add `pen` icon file
- [ ] create `EditButton` component
- [ ] apply to `EntryView` page the `EditButton` component
- [ ] update `EntryForm` component
- [ ] apply to `EntryView` page the `EntryForm` component with the necessary props

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/21)
[Next US (pending)]()

**Comment by matschi3** [comment]
and again detailed and descriptive 🚀
would say you're good to go.

it was good to check most of your previous US's
