### ISSUE TITLE
US 16: Entry Overview - Some Details

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#23]
## Value Proposition

**As a** user
**I want to** see more details per entry on the entry overview lists
**so that** I can have a quicker more precise overview of all of my entries
​

## Description

![US16-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/f13d3de4-a4df-4724-9538-4dc7770cbd5e)
​

## Acceptance Criteria

- [ ] `Entry preview` must have an icon of the Uploaded picture displayed on the left of the entry name 
- [ ] `Entry preview` must have 1 - 3 tag cards displayed underneath the entry name
      ​

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us16/entry-overview-some-details` and navigate into it
- [ ] update `EntryPreview` component

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/22)
[Next US (pending)]()
