### ISSUE TITLE
US 17: Entry Overview - Expander

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#24]
## Value Proposition

**As a** user
**I want to** click a button inside the entry overview to expand the entry details
**so that** more details of the entry are revealed to me
​

## Description

![US17-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/3ece1c8f-7415-4790-a0b4-103ecb4ac476)

## Acceptance Criteria

- [ ] `Entry preview` must have an `arrow-point-right` icon displayed on the left most side inside the `Entry preview` card
- [ ] Clicking the `arrow-point-right` icon must toggle the `Entry preview` to expand downwards to a 3x taller card and the `arrow-point-right` icon must be replaced with an `arrow-point-down` icon
- [ ] The expanded `Entry preview` must contain on the top center the entry name, undearneath it on the left side a larger thumbnail of the entry's link reference image, on the right side the entry's description (cut with `...` at the end of it if it doesn't fit), undearneath the thumbnail and the description text there should be horizontally aligned 0 - 5 tag cards of the entry
      ​

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us17/entry-overview-expander` and navigate into it
- [ ] add `arrow-point-right` icon file
- [ ] add `arrow-point-down` icon file
- [ ] update `Entry preview` component

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/23)
[Next US (pending)]()
