### ISSUE TITLE
US 18: Content List Filtering

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#32]
## Value Proposition

**As a** user
**I want to** filter through my entries
**in order to** find easier the entry I am looking for
​

## Description

![US18-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/14b8822b-0033-42af-b4bd-cad4c5570a9b)
​

## Acceptance Criteria

- [ ] `Entry preview list` must have a `filter form`
- [ ] `filter form` inside `Entry preview list` must have a text `input` field
- [ ] `filter form` inside `Entry preview list` must have a `filter by` button
- [ ] `filter by` button inside `filter form` inside `Entry preview list` must have the options options `tag text`, `name`, `description` `folder name`
- [ ] `filter form` inside `Entry preview list` must have a `search` button
- [ ] Clicking `search` button inside `filter form` inside `Entry preview list` must use the text `input` field and the `filter by` selection to make a GET request from the database specific to the provided search criteria, AFTERWARDS the `Entry preview list` should only list `Entry preview`'s matching to the filter search criteria
- [ ] `Content` page must use a property in the `Entry preview list` for the filter UI to show up

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us18/content-list-filtering` and navigate into it
- [ ] update `NewEntryList` component
- [ ] update `entries.js` api page
- [ ] update `content` page

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/24)
[Next US (pending)]()

**Comment by JonasDaJones** [comment]
Well thought out!
