### ISSUE TITLE
US 19: Content Sorting

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#33]
## Value Proposition

**As a** user
**I want to** sort the entry list
**in order to** find easier the entry I am looking for
​

## Description

![US19-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/1e0c65a1-06ef-44ce-a291-9131ed34c8a2)
​

## Acceptance Criteria

- [ ] `Entry preview list` must have `sort by` dropdown button
- [ ] `sort by` dropdown button inside `Entry preview list` must have at least the options `name`, `tag`, `description length`
- [ ] Clicking any `sort by` option must change the sorting locally with the present data and not fetch new or more data from the database   ​

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us19/content-sorting` and navigate into it
- [ ] update `NewEntryList` component

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/32)
[Next US (pending)]()

**Comment by JonasDaJones** [comment]
yup!
