### ISSUE TITLE
US 20: Entry Form - Image Upload

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#34]
## Value Proposition

**As a** user
**I want to** upload an image in my entry
**so that** my entry can properly contain a reference image for me
​

## Description

![US20-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/c52805fd-c596-4a0d-89b3-a2043ceff070)
​
> ### Left: No image selected.
> ### Right: Image selected.

## Acceptance Criteria

- [ ] `Entry form` must have an `entry image selection` field underneath the `entry name`
- [ ] Clicking `entry image selection` field inside `Entry form` must open up the conventional image file selection from the user's given device
- [ ] WHEN `entry image selection` field inside `Entry form` contains a selected image file, the `entry image selection` field must have a `remove image` button underneath
- [ ] `remove image` button inside `Entry form` must have the text `❌ Remove Image`
- [ ] Clicking `remove image` button inside `Entry form` must empty the `entry image selection` field and hide the `remove image` button
- [ ] Clicking `entry image selection` field inside `Entry form` WHEN `entry image selection` field contains a selected image file, must open up the conventioanl image file selection from the user's given device, AND allow for the selected image file to be replaced with another
- [ ] Clicking the form submit button inside `Entry form` must upload the image
      ​

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us20/entry-form-image-upload` and navigate into it
- [ ] update `EntryPreviewList` component
- [ ] (add `image` api page ?)
- [ ] update `entry.js` api page

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/33)
[Next US (pending)]()

**Comment by JonasDaJones** [comment]
once more, really detailed and thought out. Very cool!
