### ISSUE TITLE
US 21: Side Bar - Dark Mode

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#35]
## Value Proposition

**As a** user
**I want to** toggle between light and dark mode from any page
**so that** the content can be adapted to my light needs
​

## Description

![US21-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/6b02e09b-9fd7-410e-b995-26bc973e8d8e)
​

## Acceptance Criteria

- [ ] `Side bar` must have `dark mode toggle` button
- [ ] Clicking `dark mode toggle` button must switch the web app for the specific user between `dark mode` and `light mode`
      ​

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us21/side-bar-dark-mode` and navigate into it
- [ ] update `SideBar` component
- [ ] update all components styling

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/34)

**Comment by JonasDaJones** [comment]
yup
