### ISSUE TITLE
US 4: NEW FOLDER Button and Form

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#4]
## Value Proposition

**As a** user
**I want to** use a `plus` icon button from the `/` route page to navigate to `NewFolder` page which will have a folder creation form with the selection a few colors to use for my folder as well as a field to write the name of the folder and finaly a `plus` icon button on the bottom of the form to finalize the folder creation
**so that** I can create folders, but not see them yet anywhere outside the database
​

## Description

![US4-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/eff1a972-1472-4fa8-848c-f2728215f213)
​

## Acceptance Criteria

- [ ] `/` route page must have a `New Folder` button between the Dashboard `Breadcrumb` and the `RecentUploads` section text
- [ ] `New Folder` button must contain a `plus` icon inside
- [ ] `New Folder` button must have the text `New Folder` underneath the button
- [ ] Clicking the `New Folder` button must navigate me to the `New Folder` page
- [ ] `New Folder` page must have the same layout as the `Content` page regarding the `Header`, `Breadcrumb`, `Side bar`, and `Back button`
- [ ] `New Folder` page must have a `New Folder Form` 
- [ ] `New Folder Form` must have a big `folder` icon on the top center
- [ ] `New Folder Form` must have an input field for the folder name underneath the `folder` icon
- [ ] `New Folder Form` must have a color selection of 3 or more underneath the `folder name` input field
- [ ] `New Folder Form` must have a `plus` icon button on the bottom to submit the form`
- [ ] Clicking the `plus` icon submit button in `New Folder Form` must send the data to the database and navigate the user back to the `Homepage` page

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us4/new-folder-button-and-form`
- [ ] add a `plus` icon file
- [ ] create `new-folder` page file
- [ ] create `NewFolderButton` component
- [ ] create `NewFolderForm` Component
- [ ] apply to `NewFolder` page the `Header`, `Breadcrumb`, `SideBar`, and `BackButton` components with the same layout as the `content` page does
- [ ] apply to `Homepage` page the `NewFolderButton` component between the `Breadcrumb` and the `RecentUplaods` component
- [ ] apply to `NewFolder` page the `NewFolderForm` component underneath the `BackButton` component

[Previous US](#3)
[Next US (pending)](#)

**Comment by dimitriosxmi** [comment]
> Hey Dimi, just my two cents about your User Story: Maybe you can keep the value proposition much shorter, only with the needs of the user but without any technical descriptions, since you come up with this later in the criteria and the tasks. The criteria and the task description looks good 👍 Cheers, Ronald

Heyo @RonnySteady
Thank you very much for your time and for your review! 😊 
I've tried to simplify it a bit here's the _**OLD**_ and the _**NEW**_ one

from _**OLD**_
**As a** user
**I want to** use a `plus` icon button from the `Dashboard` to navigate to a folder creation page with a form contaning some buttons for a few colors to select for my folder as well as a field to write the name of the folder and finaly a `plus` icon button on the bottom of the form to finalize the folder creation
**so that** I can create folders, but not see them yet anywhere outside the database
👇 
to _**NEW**_
**As a** user
**I want to** use a button from the `Dashboard` to navigate to a folder creation page contaning some buttons colors selection of the folder as well as a field to write the name of the folder and finaly a button on the bottom of the form to finalize the folder creation
**so that** I can create folders, but not see them yet anywhere outside the database

**Comment by FelineHuhn** [comment]
Hey Dimi, nice user story 🎉 

As I am reviewing your 5th user story, I just discovered your conversation here. I would have made a similar suggestion as Sebastian, since the more detailed description of what the user sees belongs in the Acceptance criteria. 

I would suggest a value proposition something more like: 

**As a** user
**I want to** be able to add a new folder 
**so that** I can fill my dashboard with all of my projects/folders

Maybe I'll briefly summarize what we would like to read in the different sections of an user story in general 😊:

Value proposition: 
- a **short, concise** explanation of the feature in the form of 
**As a** ... (who?) e.g. user/admin/artist...
**I want to** ... (What do the user/admin/artist want? Short feature description, not detailed)
**So that** ... (Why do the user/admin/artist want this feature?) 

**Acceptance criteria:**
- you describe everything, the user should see
- you describe everything, what should happen, when the user does something e.g. clicking a button

**Tasks:**
- you describe everything, what you have to do technically step by step, to comply the acceptance criteria and whole user story / feature

**Comment by FelineHuhn** [comment]
Hi Dimi, 

the establishment of acceptance criteria for a user story can vary from team to team and from company to company. There are different approaches and practices for defining acceptance criteria.

In some cases, the acceptance criteria are discussed directly with the customer. This can be beneficial to ensure that the customer's requirements and expectations are considered and that the user story meets the desired functionality. The customer can provide important insights and contextual information that are relevant for defining the criteria.

In other cases, the acceptance criteria are developed by the product owner or product manager in collaboration with the designer and the developer. This approach is typically found in agile development teams where the product owner is responsible for defining and prioritizing the product requirements. The designer can assist in designing the user interface and user experience, while the developer considers technical aspects and feasibility. Together, they work on establishing the acceptance criteria to ensure that the user story is complete and clearly defined.

Ultimately, the specific approach depends on organizational processes, team composition, and the specific requirements of the project.

**Comment by dimitriosxmi** [comment]
> And to your value proposition, you are right, my third line is not suitable for this user story but for your next user story that I reviewed parallel 😊
> 
> But as I understand your wireframes and acceptance criteria, your feature is not the button, but to create a new folder (even if it's not displayed in the dashboard after submitting). So it should not be the button, that you describe in your value proposition, but the adding feature, or?
> 
> One more question: Like it's written in the acceptance criteria, the user jumps back to the dashboard after submitting the new folder. In addition, maybe the user should get some feedback on whether the folder creation worked after submitting, or what do you think?

Hello Feline,
excuse me if you please for my delayed response.

Thanks for the explanation regarding the works of acceptance criteria!

Now to your questions:

> But as I understand your wireframes and acceptance criteria, your feature is not the button, but to create a new folder (even if it's not displayed in the dashboard after submitting). So it should not be the button, that you describe in your value proposition, but the adding feature, or?

I see, I'm going to need your help in this, so could you please help me better understand the problem by deconstructing from your perspective as to how this:

**As a** user
**I want to** use a button from the `Dashboard`
**in order to** create a folder through a form

doesn't state the presence of both a `button` and a `folder creation feature` 

From my perspective I'd break it down to that:

**Value Proposition Breakdown**

**As a** user

Me being a user that uses this application casually without any special specific perks or criteria

---

**I want to** use a button from the `Dashboard`

My intention as a user is to click/ tap/ otherwisely use a button that seems to be located in the `Dashboard` which likely is also my location as a user in this WebApp currently.

---

**in order to** create a folder through a form

My expectation from this button usage as a user that I am is to get throwin in some way to a `form` that has it's own desired criteria and content personally I as a user don't care what they are I just want to be at the specific `form` that will ultimately allow me to `create a folder` that is new and was non existent before but will not be able to see it yet in the visualized format of the page because that is another feature I am not asking for as a user currently.

Hereby the result being that I will now have a new folder after I go through the procedure of clicking the button in the dashboard and fullfil the necessary means of input from me the user, the way I please as long as it complies with whatever form the developer has made, and submit my successfully filled form.

---
---

> One more question: Like it's written in the acceptance criteria, the user jumps back to the dashboard after submitting the new folder. In addition, maybe the user should get some feedback on whether the folder creation worked after submitting, or what do you think?

I like the idea, but that means likely one more functionality resulting to probably one more User Story, because I perhaps want to add a very elegant way to inform the user, however this sounds like a functionality that could be later stacked on top, because the current stated "feedback" is covered anyways indirectly in the next user story.

--- 

If you'd prefer more features per user story, or/ and a more composite development pattern friendly approach with the user stories, than I'd be happy to provide that in the future after the capstone project.

As of now I come to understand after many reiterations over the topic with the group and the coaches that every user story should be one feature of decent size, not too small that can be done in 5 minutes, not too big, that could realistically take a whole day.

So I have chewed the work for now in this byte sized format that consist of what seems to be 1-3 hours per user story, sorry for the inconvenience, I deem the were continuous communication issues that resulted to this 😓

**Comment by dimitriosxmi** [comment]
Note About my last comment: 
The reason I won't pack more features per User Story is because I cannot afford it time wise to restructure all my 21 User Stories summarizing to 6 pages and start over from User Story 1.
Unless you (the coach) will tell me that this User Story Structure approach I'm taking will not be tolerated and prevent me getting a certification in the end of the bootcamp. That's were I will sit down and actually restructure all the user stories and their wireframes all to a more feature enriched (per user story) and composite development friendlier approach

**Comment by nastiche** [comment]
was geht hier ab

**Comment by dimitriosxmi** [comment]
> was geht hier ab ⬆️ ❔😂

Mir wurde eine feature verlangt (die normallerweise ein eigenes user story braucht) deswegen auch der letzte kommentar wo ich über eine umstructurierung spreche die ich mir Zeitlich nicht leisten kann (außer ich arbeite 14 Stunden am tag um den Project mit alle PR reviews etc. zuende bringen zu können) Oder ich mache eine sehr schlechte app/ styling was glaub nicht wirklich erwünscht wird, weder von mir noch von der minimum requirements

Und die idee hinter der umstrukturierung ist um einige features zusammen zu packen sodass kommentare über was es schließlich sich ergibt unklarheiten gewesen zu sein, nicht immerwieder auftauchen braucht und der jeder sich mehr Zeit und energie sparen kann, das wäre der profit von eine umstrukturierung in unserem fall hier
