### ISSUE TITLE
US 5: Display Folders at Dashboard

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#5]
## Value Proposition

**As a** user
**I want to** have overview of all the folders I have displayed in the `Dashboard`
**so that** I can have a quick and easy view of the folders their names and color
​

## Description

![US5-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/daff2108-c2e8-4a66-aacc-7cda87e10d32)
​

## Acceptance Criteria

- [ ] `Homepage` page must have a list of `Folder` buttons displayed underneath the `Breadcrumb`
- [ ] `Folder` button must contain a `folder` icon
- [ ] `Folder` button must have a text containing the folder name bellow the icon
- [ ] Clicking `Folder` button must do nothing
- [ ] The displayed list must show the `New Folder` button as the last listed item

## Tasks

- [ ] switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us5/display-folders`
- [ ] create `FolderButton` component
- [ ] create `FolderList` component
- [ ] apply to `FolderList` component the `FolderButton` component
- [ ] apply to `Homepage` page the `FolderList` component underneath the `Breadcrumb`
- [ ] ensure that `New Folder` component is displayed as part of the list in the `FolderList` component and always at the end

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/4)
[Next US (pending)](#)

**Comment by FelineHuhn** [comment]
Hey Dimi, very understandable user story. Good job 🎉 I only have tiny suggestions, but they are not that important. 

**Value proposition:** 
- maybe it would be a bit more suitable, talking about the created folders and not displayed folders, since the user has created the folders before, or? So it could be written something like: 
  - **I want to** have an overview in the dashboard of all the folders I have created
  - **So that** I can have a quick and easy view of the folders (I think the mention of name and color would be enough in acceptance criteria)

**Description:**
- I really like your clearly structured wireframe

**Acceptance criteria:**
- you are very detailed, i like that! 
- I ask me, if you better should not implement a button element for the created folders, since the buttons have no functionality for now, or? You could integrate the button element in your `FolderButton` (or maybe just `Folder`?) component first, when you implement also it's functionality. 

**Tasks:**
- I would maybe rename your `FolderButton` component to only `Folder`, but that's of course a matter of taste (whereas it would be a bit weird if the component contains the word button, but it doesn't render a button element yet) 
- Do you really plan a `NewFolder` component and a `FolderButton` component, or should it read the `FolderButton` component in the last line of your tasks?

**Comment by dimitriosxmi** [comment]
> Hey Dimi, very understandable user story. Good job 🎉 I only have tiny suggestions, but they are not that important.
> 
> **Value proposition:**
> 
>     * maybe it would be a bit more suitable, talking about the created folders and not displayed folders, since the user has created the folders before, or? So it could be written something like:
>       
>       * **I want to** have an overview in the dashboard of all the folders I have created
>       * **So that** I can have a quick and easy view of the folders (I think the mention of name and color would be enough in acceptance criteria)
> 
> 
> **Description:**
> 
>     * I really like your clearly structured wireframe
> 
> 
> **Acceptance criteria:**
> 
>     * you are very detailed, i like that!
> 
>     * I ask me, if you better should not implement a button element for the created folders, since the buttons have no functionality for now, or? You could integrate the button element in your `FolderButton` (or maybe just `Folder`?) component first, when you implement also it's functionality.
> 
> 
> **Tasks:**
> 
>     * I would maybe rename your `FolderButton` component to only `Folder`, but that's of course a matter of taste (whereas it would be a bit weird if the component contains the word button, but it doesn't render a button element yet)
> 
>     * Do you really plan a `NewFolder` component and a `FolderButton` component, or should it read the `FolderButton` component in the last line of your tasks?

Heyo @FelineHuhn, thank you very much for your time and your review! 😊 

**Value Proposition**

Regarding your suggestions  on the value proposition, yeah initially I was thinking to state only folders I have created as you suggested but then I realised..
"What if when the app is finished and I am fine tuning that I wanna have say e.g. one or multiple "Default" folders? The user wouldn't have created those so it doesn't make sense to write it that way"

Also thnx for pointing out the name and color thing, thought it wouldn't bother too much given it's just 3 more words in the value proposition collectively but now I've removed them from there as well.

---

**Acceptance Criteria**

Now regarding your question at the acceptance criteria:

The folders won't have functionality as of this US you understood this corrently. The reason I decided to make them a button from now already is for 2 reasons
1. Prevent larger potential restructurings in code later on the procedure of transforming the `folder` icon elements to buttons. In other words, it's a precaution to reduce the likelyhood of bugs later.
2. To prepare the developer reading the code that this icon right here will have functionality, which is hereby quite clear as to how it will be implemented.

---

**Tasks**

Finally to the tasks:

- Yes given the explaination I've provided above within the acceptance criteria reply this wont be necessary for now
- Yes I planned as a matter of fact implemented (by the statements of the previous user story) the `NewFolder` component, hereby the developer reading this should already be aware of the existance of the `NewFolder` component if he knows anything about the WebApp that the given developer is working on more specifically in the specific page that he was hereby (this US) assigned to work on.

**Comment by actyvystom** [comment]
All in all a nice and detailed user story!
Basically I agree with @FelineHuhn concerning implementing a button component without a click functionality is useless. 
As an alternative, think of `FolderIcon` component which you can display first and add functionality later on by wrapping a button element around it or even by completely refactoring to a new component. 
**Remember:** throwing things away or rebuilding from scratch is an essential part of agile development, there is no point in thinking future iterations ahead...

**Comment by dimitriosxmi** [comment]
Heyo @actyvystom
Thank you for your time and for your review! 😊 

Given what I am understanding I have the following question risen up in my head:

Is it deemed a healthy practice in agile development to go out of you way from preventing work and bugs in the future and only focus on the very bare minimum required content to comply with the current user story even if one is aware that by the next user story, the previously built feature will be thrown partially (if not fullly) and a different feature will be replacing it? (the replacing feature, as stated, will be quite clear/ obvious to the given developer in advance before even developing the initial feature in the first place)
