### ISSUE TITLE
US 6: NEW ENTRY Button and Short Form

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#6]
## Value Proposition

**As a** user
**I want to** add an entry
**in order to** save details about my reference
​

## Description
​
![US6-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/4e55f514-dcdd-4a10-8fa3-d5a008c481cb)

## Acceptance Criteria

- [x] Both `Homepage` and `Content` must have on the bottom right of the screen a `New Entry` button and it's position must be fixed
- [x] `New Entry` button must contain a `plus` icon
- [x] Clicking `New Entry` button must navigate me to the `New Entry` page
- [x] `New Entry` page must have the same layout as the `Content` page regarding the `Header`, `Breadcrumb`, `Side bar`, and `Back button`
- [x] `New Entry` page must have  a `New Entry Form`
- [x] `New Entry Form` must have an input field for the entry name on the top center
- [x] `New Entry Form` must have a `plus` icon button on the bottom to submit the form`
- [x] `New Entry Form`'s entry name input field must be required in order to submit the form
- [x] Clicking the `plus` icon submit button in the `New Entry Form` must send the data to the database and navigate the user back to the `Homepage`
      ​

## Tasks

- [x] switch to `main` branch and perform a `git pull` in the terminal
- [x] create the branch `feature/us6/new-entry-button-and-form`
- [x] create `new-entry` page file
- [x] create `NewEntryButton` component
- [x] create `NewEntryForm` component
- [x] apply to `NewEntry` page the `Header`, `Breadcrumb`, `SideBar`, and `BackButton` components with the same layout as the `Content` page does
- [x] apply to `Homepage` and to `Content` page the `NewEntryButton` component on the button right fixed position of the screen
- [x] apply to `NewEntry` page the `NewEntryForm` component underneath the `Breadcrumb` component

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/5)
[Next US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/7)

**Comment by RonnySteady** [comment]
Hi Dimi, 
plausible and very detailed user story in acceptance criteria and tasks. Because I was told so often: the value proposition is quite technical (buttons, content pages), can be more like "I want to add entries from everywhere in the app" (you know what I mean). 
Also I was a bit confused about several add buttons with + symbol with different functions (add folder, add entry and submit entry). How about using another symbol for creating a folder and a label "Save" or "Submit" for the button?

**Comment by dimitriosxmi** [comment]
> Hi Dimi, plausible and very detailed user story in acceptance criteria and tasks. Because I was told so often: the value proposition is quite technical (buttons, content pages), can be more like "I want to add entries from everywhere in the app" (you know what I mean). Also I was a bit confused about several add buttons with + symbol with different functions (add folder, add entry and submit entry). How about using another symbol for creating a folder and a label "Save" or "Submit" for the button?

Heyo Ronald,
Thank you very much for your time and for your review! 😊 

Regarding the Value Proposition:
I merely used the normal names the user will know by now such as `Dashboard` and `Content` pages, hereby I am not using any technical terms just the rough names which the average user will have encountered plenty of times by now 😛

Regarding the Confusion:

>Also I was a bit confused about several add buttons with + symbol with different functions (add folder, add entry and submit entry). How about using another symbol for creating a folder and a label "Save" or "Submit" for the button?

You are making a good point regarding the potential confusion, and I just experimented a bit around in any way I'll need to add bunch of text around to make everything verbosely self-explanatory.
However I've decided to stick with eveything being the plus icon cause that just works much better to be frank.

E.g.:

- In the Dashboard you see on the top side, there is a plus button with a new folder text underneath, that one explains itself in a verbose manner
- Next there is the plus button on the bottom of the dashboard screen if you look a bit higher you'll see the smaller headline "No uploaded files yet", so as a user I could assume that "Ah this might be related since there is no other hint around as to what that plus button does"
- Last we have the New Entry page having it's own single big Plus button on the bottom of the page and the (New Entry) Breadcrumb on top of the page with 1 or multiple input fields in between, so likely this is the button to send off a new entry that was just created, the design is similar to #4  so the cocept should be quite understandable

---

Given this example it seems as the only unclear button is the New Entry button, best I can do design wise on that without ruining too badly the design is one of these, what do you prefer ?

![US6-ARO_Alt-Buttons](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/2a0db93d-fcec-48c3-845e-07a6691434bb)

#### Note: The icons on the right image may vary from the ones used later in the production

**Comment by actyvystom** [comment]
Hi Dimi, 
a nice one, I like the detailed way you define your acceptance criteria and your tasks!

I do struggle with your **value proposition** and agree with Ronald that it contains a technical description. Think of a (really dumb) user who is even not aware that this thing to press is called a button and that they don't know what a dashboard is... Keeping this in mind, I would suggest something like the following as value proposition:

> As a user
> I want to be able to add a collection/folder for my references
> so that I am able to set up a new section for collecting my references        

Cheers, Thomas

**Comment by dimitriosxmi** [comment]
> Hi Dimi, a nice one, I like the detailed way you define your acceptance criteria and your tasks!
> 
> I do struggle with your **value proposition** and agree with Ronald that it contains a technical description. Think of a (really dumb) user who is even not aware that this thing to press is called a button and that they don't know what a dashboard is... Keeping this in mind, I would suggest something like the following as value proposition:
> 
> > As a user
> > I want to be able to add a collection/folder for my references
> > so that I am able to set up a new section for collecting my references
> 
> Cheers, Thomas

Heyo good morning Thomas,
Thank you very much for your time and for the review! 😊 

Fun fact, I don't know even know what a dashboard is 😆 I mean I've seen what many sites wants to call a dashboard, but I don't actually know what this is supposed to be 😋 

Regarding the suggestion it seems that you confused this Userstory with #4 hehe
but okay so in this case I want to add the entry creation button and form (not the list to view it though, that's for the next userstory #7 
so how about this value proposition

# From _**OLD**_ ❌ 

**As a** user
**I want to** use a button from both `Dashboard` and `Content` pages
**in order to** create an entry through a form

# To _**NEW**_ ✅ 👇 

**As a** user
**I want to** add an entry
**in order to** save details about my reference

**Comment by CarstenJahnke** [comment]
LGTM Bro! 🎉
