### ISSUE TITLE
US 8: Folder View

### ISSUE THREAD

**Issue by dimitriosxmi** [dimitriosxmi/ArtistsReferenceOrganizer#8]
## Value Proposition

**As a** user
**I want to** click on a folder to enter the folder view
**in order to** see the entries it contains or create new ones for the folder by hitting the entry creation button
​

## Description

![US8-ARO](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/258f248a-35f4-4fde-87ba-4ca0232b54d9)

---

![US8-ARO_Content Reference](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/assets/31593501/b860b92f-9be7-4a58-8390-0822466e5899)
> ## Here's a content page reference:

## Acceptance Criteria

- [ ] `FolderIcon` must now become `Folder button`
- [ ] `Folder button` must contain a button
- [ ] Clicking `Folder button` must navigate me to the corresponding `Folder view` page
- [ ] `Breadcrumb` when located in `Folder view` page must be something similar to `Dashboard/ folder/ <folderName>`
- [ ] `Folder view` page must have the same layout as the `Content` page does regarding the `Header`, `Breadcrumb`, `Side bar`, `Back button`, and `New Entry`
- [ ] `Folder view` page must have a list of `EntryIcon` displayed underneath the `Breadcrumb`
- [ ] `EntryIcon` list in the `Folder view` page must only show the `EntryIcon`'s that have the current folder's id as their `selectedFolder` property
- [ ] using `New Entry` button inside the `Folder view` page must assign the entry's folder to the current folder
      ​

## Tasks

- [ ]  switch to `main` branch and perform a `git pull` in the terminal
- [ ] create the branch `feature/us8/folder-view`
- [ ] change `FolderIcon` to `FolderButton`
- [ ] update `FolderButton` component
- [ ] create `FolderView` page file
- [ ] apply to `FolderView` page the `Header`, `Breadcrumb`, `SideBar`, `BackButton`, and `NewEntry` components with the same layout as `Content` page does
- [ ] update `EntryList` component
- [ ] apply to `FolderView` page the `EntryList` component underneath the `BackButton` component
- [ ] update `NewEntry` component

[Previous US](https://github.com/dimitriosxmi/ArtistsReferenceOrganizer/issues/7)
[Next US (pending)](#)

**Comment by CarstenJahnke** [comment]
LGTM Bro! 🎉

**Comment by dimitriosxmi** [comment]
> LGTM Bro! 🎉

Thanks for the review bro!
